import { Metrics, Palette } from "../global/theme.g.slint";
import { ColumnSpec } from "../structs/column_spec.slint";
import { ColumnConfig } from "../global/column_config.slint";
import { HeaderCell } from "header_cell.slint";
import { OrderByUi } from "../enums/order_by.slint";

export component ProcessTableHeader inherits Rectangle {
    height: Metrics.header-height;
    background: Palette.header-bg;

    //callback => functions.
    callback sort-requested(OrderByUi);

    HorizontalLayout {
        padding: Metrics.cell-padding;
        spacing: Metrics.cell-spacing;

        HeaderCell {
            title: "Name";
            horizontal-stretch: 1;
            clicked => { root.sort-requested(OrderByUi.Name); }
        }

        for column[index] in ColumnConfig.columns: HeaderCell {
            title: column.title;
            alignment: column.alignment;
            width: column.width;
            clicked => { root.sort-requested(column.order-by); }
        }
    }

    Rectangle {
        y: parent.height - 1px;
        height: 1px;
        background: Palette.border;
    }
}
